# Docker Compose configuration for SENTINEL
services:
  # Main SENTINEL monitoring service
  sentinel:
    # Build configuration
    build:
      context: .
      dockerfile: Dockerfile
      target: runtime  # Use runtime stage for prod
      args:
        - BUILDKIT_INLINE_CACHE=1

    # Container metadata
    container_name: sentinel-monitor
    hostname: sentinel

    # Restart policy
    restart: unless-stopped

    # Networking
    networks:
      - sentinel-network

    # Port configuration
    ports:
      - "8080:8080"

    # Volume mounts
    volumes:
      # Configuration file (read-only for security)
      - ./sentinel.yaml:/app/sentinel.yaml:ro

    # Environment variables
    env_file:
      - .env
    # environment:
    #   # Notification service tokens (optional, for future features) - todo
    #   - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN:-}
    #   - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID:-}
    #   - DISCORD_WEBHOOK_URL=${DISCORD_WEBHOOK_URL:-}
    #   # Application settings
    #   - DB_PATH=/app/data/sentinel.db
    #   # Disable CGO for static binary
    #   - CGO_ENABLED=0

    # Health check configuration - robust for production
    healthcheck:
      test: ["CMD-SHELL", "./sentinel once > /dev/null 2>&1 || exit 1"]
      interval: 60s
      timeout: 15s
      retries: 3
      start_period: 30s

    # Resource management - optimized for lightweight app
    deploy:
      resources:
        limits:
          # Conservative limits for monitoring app
          cpus: '0.5'
          memory: 64M
        reservations:
          cpus: '0.1'
          memory: 32M

    # Logging configuration
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "3"
        compress: "true"

    # Security configuration
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    read_only: true
    tmpfs:
      - /tmp:noexec,nosuid,size=100m
      - /app/data:noexec,nosuid,size=50m

networks:
  sentinel-network:
    driver: bridge
    internal: false

volumes:
  # Persistent storage for future database features
  sentinel_data:
    driver: local
